trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'az-Subscription'
      KeyVaultName: 'azkeyvault-001'
      SecretsFilter: 'eventhubname,eventhubstring'
      RunAsPreJob: true

  - script: |
      python src/test2.py
    displayName: 'Run crypto ingestion script'
